### ISSUE TITLE
Empty string as enum value

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1057]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

The RAML specification doesn't explain how enum works in details, so this goes as a question. 

* **What is the current behavior?**

In other validation tool I've got an error that `enum: [""]` contains an invalid value, while AMF validates it without any issues. So the question is: is it expected behavior?

Example RAML:
```yaml
#%RAML 1.0
title: Enum type with empty value

types:
  StringEnumType:
    type: string
    enum:
      - ""
      - "ONE"

/person:
  get:
    body:
      application/json:
        type: StringEnumType
        example: ""
```

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.5
  - AMF Distribution: JVM 
  - Operating System: Windows 10 21H1
