### ISSUE TITLE
'type' facet allows nested 'type'

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1085]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

The following RAML is validated and parsed successfully:
```yaml
#%RAML 1.0
title: Test API

/person:
  post:
    body:
      application/json:
        type:
          type:
            type:
              type: object
              properties:
                prop1: string
```

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

* **What is the expected behavior?**

Such use of the facet doesn't seem to be correct as it is supposed to allow only data types.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.6
  - AMF Distribution: JVM and JS
  - Operating System: Windows 10 21H1

**Comment by tomsfernandez** [comment]
Hi @deiteris, can you point out where in the spec it says this is not allowed?

According to https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#type-declarations in the `type` facet entry:

> The type which the current type extends or just wraps. The value of a type node MUST be either a) the name of a user-defined type or b) the name of a built-in RAML data type (object, array, or one of the scalar types) or c) an inline type declaration.

**Comment by deiteris** [comment]
Hi @tomsfernandez. Just to make sure we're on the same page (as my example may be unclear): I am considering as a bug the following construct that is allowed by AMF parser:
```yaml
types:
  MyType:
    type:
      type:
        # And many more nested 'type:' facets below until the actual type value.
```
And according to your cite from the spec it accepts **a value** (that is one of the possible listed values), not the other facets. 

This may become especially confusing when deprecated `schema` keyword is being mistakenly used to describe a type (I've recently stumbled upon this usage and that's the whole reason why I am reporting this) like this, since these facets are equal:
```yaml
types:
  MyType:
    schema:
      type: object
      properties:
```
