### ISSUE TITLE
Custom domain property 'tags' disappears from the model

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1086]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

Given the following RAML:

```yaml
#%RAML 1.0
title: Test API
baseUri: https://example.com
protocols:
  - HTTPS

annotationTypes:
  tags:
    type: string

/pets:
  get:
    (tags): test
```

When parsed, the `(tags)` annotation disappears from the endpoint method. This doesn't seem to happen with annotation types that have different names.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

Here's the repo that reproduces the issue: https://github.com/deiteris/amf-gh-issue-1

1. Clone the repo.
1. Run `npm i` to install package dependencies.
1. Run `node amf-parser.js`.

The output will be as follows. Notice that `tags` is missing for `api_tags.raml`, but `xtags` is present for `api_xtags.raml`:
```
/pets
   get
---------------
/pets
   get
     xtags
```

* **What is the expected behavior?**

Custom domain property `tags` should be listed for endpoint method.

* **Please tell us about your environment:**
  
  - AMF Version: 4.0.3 (JS), 4.7.6 (JVM and JS)
  - AMF Distribution: JVM and JS 
  - Operating System: Windows 10 21H1
