### ISSUE TITLE
JSON schema of scalar type causes java.RuntimeException when defined with 'type' facet and used in response body

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1121]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

If a JSON schema, that defines validation of a scalar type, is defined with `type` facet and used in response body, it causes java.RuntimeException.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

The following RAML reproduces the issue:
```yaml
#%RAML 1.0
title: Test API
baseUri: https://example.com
protocols:
  - HTTPS

types:
  ScalarJsonSchema:
    type: |
      {
        "type": "string"
      }

/pets:
  get:
    responses:
      200:
        body:
          application/json:
            type: ScalarJsonSchema
```

Causes the following exception message: `java.lang.RuntimeException: Undefined type def`

* **What is the expected behavior?**

This error should be handled gracefully at least, otherwise it's hard to tell where the problem occurred.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.7 / 4.7.6
  - AMF Distribution: JVM and JS 
  - Operating System: Windows 10 21H1

**Comment by stenri** [comment]
According to my tests, this issue also affects AMF 5.0.0-beta.4-1.

**Comment by nschejtman** [comment]
@deiteris @stenri I confirm this is a bug. As a workaround, extracting the schema to an external file and including it works fine. Created APIMF-3387 in our internal Jira to track this, let you know when we have any updates.

**Comment by deiteris** [comment]
> @deiteris @stenri I confirm this is a bug. As a workaround, extracting the schema to an external file and including it works fine. Created APIMF-3387 in our internal Jira to track this, let you know when we have any updates.

@nschejtman, just to clarify, the same issue happens if you also extract it to file. For example:
```yaml
types:
  ScalarJsonSchema:
    type: !include scalar_json_schema.json # Contains {"type": "string"}
```

The issue does not occur, when JSON schema is directly assigned to a type. In the following example, both will work fine:
```yaml
types:
  ScalarJsonSchemaExternal: !include scalar_json_schema.json
  ScalarJsonSchemaInline: |
      {
        "type": "string"
      }
```
