### ISSUE TITLE
How validation actually works with updated interface?

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1186]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

* **What is the current behavior?**

According to the current documentation (https://a.ml/docs/amf/using-amf/amf_validation/), the following usage should be followed when parsing and validating the model:

```js
const amf = require('amf-client-js');

(async () => {
    const sourceFile = `
#%RAML 1.0
title: My API

uses:
    nonExistingLib: ./someLib/lib.raml # <-- This library doesn't exist and should be reported as invalid
    `;

    const client = amf.RAMLConfiguration.RAML10()
        .withRenderOptions(new amf.RenderOptions().withoutSourceMaps().withCompactUris().withoutPrettyPrint())
        .baseUnitClient();

    // Using parseContent() to fit everything in the code
    const parsingResult = await client.parseContent(sourceFile);
    const validationResult = await client.validate(parsingResult.baseUnit);
    console.log(validationResult.toString());
})();
```

The validation report will output the following result that should not be possible:
```yaml
ModelId: http://a.ml/amf/default_document
Profile: RAML 1.0
Conforms: true
Number of results: 0
```

I've spent few hours figuring out how can this possibly happen, then I looked up the typescript declarations and found that parsing functions already return a validation report within `AMFResult`, making `client.validate()` call kind of redundant in this case. By replacing `validationResult` with `parsingResult` I was able to achieve the expected validation report (though profile is missing in this case):

```yaml
Model: http://a.ml/amf/default_document
Conforms: false
Number of results: 1

Level: Violation

- Constraint: http://a.ml/vocabularies/amf/core#unresolved-reference
  Message: Network Error: Unexpected status code '301' for resource 'http://a.ml/amf/default_document/someLib/lib.raml'
  Severity: Violation
  Target: ./someLib/lib.raml
  Property:
  Range: [(6,20)-(6,38)]
  Location: http://a.ml/amf/default_document
```

So the question: is this how I actually should use the new interface? Or there's something wrong?

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.0
  - AMF Distribution: JS 
  - Operating System: Windows 10 21H1

**Comment by tomsfernandez** [comment]
Hi @deiteris. In AMF 4.x.x, "validation" includes different types of errors:
- Parsing errors
- "Model" errors: inconsistencies or fields that are required that aren't present
- Invalid examples or enums.

In AMF 5.x.x, "parsing" errors are returned after parsing only, not when running "validation".

To have the "legacy" behaviour you can call the `merge` method in the `AMFResult` to add the AMFValidationReport obtained by calling `validation`.

```javascript
const parsingResult = await client.parseContent(sourceFile);
const validationResult = await client.validate(parsingResult.baseUnit);
console.log(parsingResult.merge(validationResult).toString());
```

**Comment by deiteris** [comment]
Great! This seems to be what I was looking for. It gives me the expected output, but the profile is still missing though:
```yaml
Model: http://a.ml/amf/default_document
Conforms: false
Number of results: 1

Level: Violation

- Constraint: http://a.ml/vocabularies/amf/core#unresolved-reference
  Message: Network Error: Unexpected status code '301' for resource 'http://a.ml/amf/default_document/someLib/lib.raml'
  Severity: Violation
  Target: ./someLib/lib.raml
  Property:
  Range: [(6,20)-(6,38)]
  Location: http://a.ml/amf/default_document
```

Anyways, your answer also gave me an idea that I can check for parsing errors and output them first, then output model errors if there are any. Thanks!
