### ISSUE TITLE
RAML Library References `uses:` lost after export

### ISSUE THREAD

**Issue by jgsuess** [aml-org/amf#1304]
Your issue may already be reported! Please search on Github issues before creating one.

When reading a RAML File that contains imports of libraries, the reference to the library types are reflected, but no `uses:` directives are contained.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

When reading a RAML File that contains imports of libraries, the reference to the library types are reflected, but no `uses:` directives are contained.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

Read a RAML file that references a library via includes into the parser, then export it via generation.

* **What is the expected behavior?**

`uses:` directives pointing to the libraries are included in the exported file.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

I need to parse the library includes within a large library.

* **Please tell us about your environment:**
  
  - AMF Version: 4
  - AMF Distribution: JVM
  - Operating System: ubuntu
  - Link to your project: commercial

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, Gitter, etc)

**Comment by looseale** [comment]
Hi.
I tried to reproduce this with the last version of AMF (5.0.3) and is working for me.
I used this code:
``` 
val configuration: AMFConfiguration = RAMLConfiguration.RAML10()
val unitClient: AMFBaseUnitClient = configuration.baseUnitClient()
val baseUnit: BaseUnit = unitClient.parse(input).get().baseUnit
val rendered: String = unitClient.render(baseUnit)
```

with this API:

```
api.raml
#%RAML 1.0

title: asdasd
uses:
  lib: lib.raml
types:
  SomeType: lib.SomeType

lib.raml
#%RAML 1.0 Library

usage: use it
types:
  SomeType:
    type: object
    properties:
      a: string
      b: integer
```

and the rendered content was

```
#%RAML 1.0
title: asdasd
types:
  SomeType: lib.SomeType
uses:
  lib: lib.raml
```

Are you resolving/transforming the BaseUnit?

Also, I recommend you to move to the last version. Any non critical bug fixing will not be ported to AMF 4.x.x (we will only fix security issues in AMF 4 basically).
You can find a little migration guide here https://a.ml/docs/amf/migration_guide and examples of most of the features in AMF4 vs AMF5 here https://github.com/aml-org/examples
