### ISSUE TITLE
Discriminator value is not validated

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1453]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

The `discriminatorValue` property is not validated against the type of the `discriminator` field.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

The following RAML file reproduces the issue:
```yaml
#%RAML 1.0
title: Pets API

types:
  Pet:
    type: object
    discriminator: type
    discriminatorValue: true
    properties:
      type: integer
```

* **What is the expected behavior?**

`discriminatorValue` should be validated against the `discriminator` field type.

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.9
  - AMF Distribution: JVM and JS 
  - Operating System: Windows 10 21H2
