### ISSUE TITLE
Range of dialect definitions and !include / !extend

### ISSUE THREAD

**Issue by antoniogarrote** [aml-org/amf#151]
This issue reviews the semantics of `range` for object properties after the introduction of the !extend keyword.

The facet `range` can be used to set the range of a property to be literal (not reviewed in this issue) or a target node mapping reference.

The target node can be define:

- with class and properties

```
nodeMappings:
  
  A:
    classTerm: vocab.A
    mapping:
      a:
       propertyTerm: vocab.a
       range: string

  B:
    classTerm: vocab.B
    mapping:
      b:
        propertyTerm: vocab.b
        range: A # A node has class and property restrictions
```

- Only properties

```
nodeMappings:
  
  A:
    mapping:
      a:
       propertyTerm: vocab.a
       range: string

  B:
    classTerm: vocab.B
    mapping:
      b:
        propertyTerm: vocab.b
        range: A # A node has only properties
```

- Only class term:

```
nodeMappings:
  
  A:
    classTerm: vocab.A

  B:
    classTerm: vocab.B
    mapping:
      b:
        propertyTerm: vocab.b
        range: A # A node has only class term
```

- the special `AnyNode` reference:

```
nodeMappings:

  B:
    classTerm: vocab.B
    mapping:
      b:
        propertyTerm: vocab.b
        range: AnyNode
```

Each of this definitions have an impact in the triples that will be generated:

- if class and properties are defined, triples for `rdf:type` and property triples will be generated
- if only class is present, only the `rdf:type` triple  will be generated
- if only properties are present only property tripels will be generated (not rdf:type)

This will also have an impact on the validation of the target node, because only type, properties or both of them will be parsed.

AnyNode has an special behaviour that can be used to link any external fragment using `!extend`.
In this case the linked fragment will be parsed (using the fragment header or explicit dialect link in the fragment header) and the parsed graph will be linked wihout further validation under the property in the range.

If the user is linking a fragment using !extend all the available information fro the constraints of the node will be used to validate the linked fragment.

- if `AnyNode` is used, no local validation will be performed.
- if only `classTerm` facet is used, the fact that the graph for the remoter fragment is an instance of the class will be validated
- if only properties are defined, constraints for each of the properties will also be validated over the remote fragment graph
- if both classTerm and properties are locally defined all those constraints will be validated additionally to the remote fragment validation.

A note about the constraint validation implementation. All this must be possible to validate using SHACL shapes after resolution. No local ad-hoc validation code must be added.
