### ISSUE TITLE
JSON definitions and RAML types names collision

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1519]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

When working with RAML documents that heavily rely on JSON schemas, there's a possible namespace collision when defining a type definition in JSON schemas and RAML types in RAML documents. The same issue may also happen when different JSON schemas have same names in their own definitions.

This results in unpredictable behavior, where JSON schema type or RAML type can override each other and producing misleading validation result.

The following document produces an example validation error. The example is correct according to the `Customer` schema, but the `AccessRole` RAML type is used instead of the `AccessRole` defined in JSON schema:
```yaml
#%RAML 1.0

title: Customers API
version: 1.0
mediaType: application/json

types:
  AccessRole:
    type: object
    properties:
      name: string
      attributes: array
  Customer: |
    {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "definitions": {
            "AccessRole": {
                "type": "string",
                "enum": [ "CA", "NY" ]
            }
        },
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "role": {
              "$ref": "#/definitions/AccessRole"
            }
        },
        "required": ["name", "role"]
    }

/customers:
  displayName: Customer Resource
  get:
    body:
      type: Customer
      example: |
        {
          "name": "MyName",
          "role": "CA"
        }
```
![image](https://user-images.githubusercontent.com/6103913/181746569-04d202d5-ba74-4610-ad78-cbfee3e8cb93.png)

* **What is the expected behavior?**

To avoid confusion, validator should check for duplicate type names and emit a corresponding validation message.

* **Please tell us about your environment:**
  
  - AMF Version: 5.0.11
  - AMF Distribution: JS 
  - Operating System: Windows 10 21H1
