### ISSUE TITLE
unresolved-reference context Boxed Error

### ISSUE THREAD

**Issue by dcrossleyau** [aml-org/amf#1569]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **Please tell us about your environment:**
  
  - AMF Version: v5.0.12
  - AMF Distribution: amf-client-js
  - Operating System: macOS Catalina and Ubuntu with node.js 14.20.0
  - Link to your project: [folio-org/mod-inventory](https://github.com/folio-org/mod-inventory/blob/master/ramls/inventory.raml)

---

One of our RAML-based projects is yielding a strange parsing violation:

```
- Constraint: http://a.ml/vocabularies/amf/core#unresolved-reference
  Message: Boxed Error
```

I have trimmed the RAML and schema down as much as i dare. (If needed, then the full resources are [here](https://github.com/folio-org/mod-inventory/blob/master/ramls/inventory.raml).)

See [context-boxed-error.tar.gz](https://github.com/aml-org/amf/files/9460168/context-boxed-error.tar.gz)

The trimmed inventory.raml

```
#%RAML 1.0
title: Inventory API (reduced for AMF bug report)

types:
  instance: !include instance.json
  instances: !include instances.json

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/inventory:
  /instances:
    type:
      collection:
        exampleCollection: !include examples/instances_get.json
        schemaCollection: instances
        schemaItem: instance
        exampleItem: !include examples/instance_get.json
    get:
    /{instanceId}:
      type:
        collection-item:
          exampleItem: !include examples/instance_get.json
          schema: instance
      get:
```

Those "resourceTypes" are in a shared "raml-util" directory, which is utilised across our 80+ RAML-based projects. The AMF client has no trouble with that elsewhere.

This is the reduced script used to parse and validate. \
Do: `node validate.js ramls/inventory.raml`

```javascript
const amf = require('amf-client-js');
const inputFn = process.argv[2];
const client = amf.RAMLConfiguration.RAML10().baseUnitClient();
async function main() {
  const parsingResult = await client.parseDocument(`file://${inputFn}`);
  const validationResult = await client.validate(parsingResult.baseUnit);
  console.log('---- parsingResult:');
  console.log(parsingResult.toString());
  console.log('---- validationResult:');
  console.log(validationResult.toString());
  if (!parsingResult.conforms || !validationResult.conforms) {
    process.exitCode = 1;
  }
}
main();
```

This is the parsing and validation result (using amf-client-js v5.0.12):

```
---- parsingResult:
Model: file://ramls/inventory.raml
Conforms: false
Number of results: 2

Level: Violation

- Constraint: http://a.ml/vocabularies/amf/core#unresolved-reference
  Message: Boxed Error
  Severity: Violation
  Target: examples/instance_get.json
  Property: 
  Range: [(19,21)-(19,56)]
  Location: file://ramls/inventory.raml

- Constraint: http://a.ml/vocabularies/amf/core#unresolved-reference
  Message: Boxed Error
  Severity: Violation
  Target: examples/instance_get.json
  Property: 
  Range: [(24,23)-(24,58)]
  Location: file://ramls/inventory.raml

---- validationResult:
ModelId: file://ramls/inventory.raml
Profile: RAML 1.0
Conforms: true
Number of results: 0
```

The schema and example can be independently verified:

```
z-schema --pedanticCheck instance.json examples/instance_get.json
schema validation passed
json #1 validation passed
```

The JSON examples/instance_get.json has a `"@context"` property.

The JSON examples/instances_get.json is similar with multiple records, but there a no violation reported from that.

If we temporarily remove that `"@context"` property from the examples/instance_get.json file, then there are no violations reported.

We have no idea what is meant by "Boxed Error" and searching does not seem to assist.
