### ISSUE TITLE
Non literal types are not honored

### ISSUE THREAD

**Issue by vromero** [aml-org/amf#166]
Defining a vocabulary term with:

```yaml
createdAt:
    displayName: createdAt
    description: Date and time when the repository was created
    range: dateTime
```

In a dialect:

```yaml
createdAt:
        propertyTerm: about-github.createdAt
        range: string
```

Ends up creating a triple like this:

```json
"http://mulesoft.com/vocabularies/about-github#createdAt": [
          {
            "@value": "2012-12-31T23:57:00"
          }
        ],
```

Note the lack of `^^xsd:dateTime` after the literal.
