### ISSUE TITLE
A RAML file referencing a security scheme in a library is converted into an invalid OAS3 file

### ISSUE THREAD

**Issue by profj-higgo** [aml-org/amf#1664]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

A RAML file which references a security scheme in a library is converted by AMF into an invalid OAS3 file.  

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

I have created a small github project to demonstrate the problem [https://github.com/profj-higgo/amf-bug-securedby](https://github.com/profj-higgo/amf-bug-securedby).   The repository contains a test "RamlToOasConversionTest" which you can run and it will fail because the generated OAS3 file is invalid.  After you have run the test the generated OAS3 file can be found in the directory "src/test/resources/demo-api/".

The sample project has a RAML library which contains a security scheme.

```
#%RAML 1.0 Library

securitySchemes:
  basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication
```

The RAML file references the security scheme using "securedBy".

```yaml
uses:
  lib: raml-library.raml
```

```yaml
/accounts:
  get:
    securedBy:
      - lib.basic
```

The RAML file is converted successfully to an OAS3 file by AMF but the OAS3 file fails validation.

Code to generate the OAS3 file:

```java
final AMFBaseUnitClient inputFileClient = APIConfiguration.API().baseUnitClient();
AMFDocumentResult parseResult = inputFileClient.parseDocument( pathToRamlFile.toUri().toString() ).get();
AMFBaseUnitClient oas30Client = OASConfiguration.OAS30().baseUnitClient();
final BaseUnit transformedOas3Model = oas30Client.transform( parseResult.baseUnit() ).baseUnit();
final String oasJsonOutputString = oas30Client.render( transformedOas3Model ).trim();
```

Code to validate the OAS3 file:

```java
final AMFBaseUnitClient oasClient = OASConfiguration.OAS30().baseUnitClient();
final BaseUnit model = oasClient.parse( pathToOasFile.toUri().toString() ).get().baseUnit();
AMFValidationReport report = oasClient.validate( model ).get();
```

Validation error:

```
Profile: OAS 3.0
Conforms: false
Number of results: 1

Level: Violation

- Constraint: http://a.ml/vocabularies/amf/parser#SecurityScheme-type-minCount
  Message: Type is mandatory in a Security Scheme Object
  Severity: Violation
  Target: file:///C:/Users/Tom/IdeaProjects/amf-bug-securedby/src/test/resources/demo-api/api.json#/web-api/endpoint/%2Faccounts/supportedOperation/get/security/requirement_1/schemes/lib.basic/scheme/fragment
  Property: http://a.ml/vocabularies/security#type
  Range: 
  Location: 
```

I am using:

```
<groupId>com.github.amlorg</groupId>
<artifactId>amf-api-contract_2.12</artifactId>
<version>5.2.1</version>
```

* **What is the expected behavior?**

The generated OAS3 file should be valid.

* **What is the motivation/use case for changing the behavior? (for feature requests)**

N/A

* **Please tell us about your environment:**
  
  - AMF Version: 5.2.1
  - AMF Distribution: JVM
  - Operating System: Windows 10
  - Link to your project: https://github.com/profj-higgo/amf-bug-securedby

* **Other information** 

Please review the github sample project and run the tests.
