### ISSUE TITLE
Derived object's property doesn't take precedence over parent's pattern property

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1735]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

When parent object type defines pattern properties of a specific type and derived types specifies a property, specified property validation doesn't take precedence over the pattern property. I've found several cases when the rule is not followed correctly.

If it will be more convenient, I can split cases on separate github issues.

Case 1: The following RAML demonstrates this behavior when pattern property is array and derived object explicitly declares a property of a scalar type:
```yaml
#%RAML 1.0 Library

annotationTypes:
  instance: SpecializedStrObject

(instance):
  # OK: Changing this to "xyz" will fail validation with "prop1 should match pattern "^abc$" (http://a.ml/vocabularies/amf/validation#example-validation-error)"
  prop1: abc # Not OK: Throws "['prop1'] should be array (http://a.ml/vocabularies/amf/validation#example-validation-error)"

types:
  PatternObject:
    properties:
      //:
        type: array
        items:
          type: string

  SpecializedStrObject:
    type: PatternObject
    additionalProperties: false
    properties:
      prop1:
        type: string
        pattern: ^abc$
```

Case 2: The following RAML demonstrates this behavior when pattern property is array and derived object explicitly declares a property of an array type:
```yaml
#%RAML 1.0 Library

annotationTypes:
  instance: SpecializedIntObject

(instance):
  prop1: # Not OK: Throws "['prop1'][0] should be string (http://a.ml/vocabularies/amf/validation#example-validation-error)"
    - 0

types:
  PatternObject:
    properties:
      //:
        type: array
        items: string

  SpecializedIntObject:
    type: PatternObject
    additionalProperties: false
    properties:
      prop1:
        type: array
        items: integer
```

Case 3: The following RAML demonstrates this behavior when pattern property is a string and derived object explicitly declares a property of some other type (f.e., integer):
```yaml
#%RAML 1.0 Library

annotationTypes:
  instance: SpecializedIntObject

(instance):
  # OK: Throws "prop1 should be integer (http://a.ml/vocabularies/amf/validation#example-validation-error)"
  # Not OK: When changing to integer, throws "['prop1'] should be string (http://a.ml/vocabularies/amf/validation#example-validation-error)"
  prop1: str

types:
  PatternObject:
    properties:
      //: string

  SpecializedIntObject:
    type: PatternObject
    additionalProperties: false
    properties:
      prop1: integer
```

For comparison, similar RAML that defines pattern property with plain string type is validated correctly:
```yaml
#%RAML 1.0 Library

annotationTypes:
  instance: SpecializedStrObject

(instance):
  # OK: Changing this to "abc" will pass the validation
  prop1: xyz # OK: Throws "prop1 should match pattern "^abc$" (http://a.ml/vocabularies/amf/validation#example-validation-error)"

types:
  PatternObject:
    properties:
      //:
        type: string

  SpecializedStrObject:
    type: PatternObject
    properties:
      prop1:
        type: string
        pattern: ^abc$
```

* **What is the expected behavior?**

Explicitly declared property type should take precedence when validating the pattern properties as per RAML 1.0 specification (https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#additional-properties). But it's not clear if it's also applicable to the derived object type:
```
If a pattern property regular expression also matches an explicitly declared property, the explicitly declared property definition prevails.
```

* **Please tell us about your environment:**
  
  - AMF Version: 5.2.4
  - AMF Distribution: JS and JVM
  - Operating System: Windows 10 22H2

**Comment by arielmirra** [comment]
hi @deiteris! This is a bug, but this issue is related to inheritance resolution, and we're going through a big refactor in that regard. Therefore, I've created an [internal issue](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001MrHhbYAF/view) but put it on hold until this is done. I'll take some time, we'll update you when it's done.

**Comment by arielmirra** [comment]
Hi @deiteris! I've got updates:
This is not due to inheritance resolution, that only merges the properties like so:
```yaml
#%RAML 1.0
title: New API

annotationTypes:
  instance: SpecializedIntObject

(instance):
  prop1: 123

types:
  SpecializedIntObject:
    type: object
    properties:
      //: string
      prop1: integer
```

This API also has this issue, but the problem is that we derive payload validation to the everit validator that receives JSON-LD, and in the json draft 7 schema spec the behavior of pattern properties contradicts that specified in the RAML spec, but in validation time we can't know we're coming from RAML 1.0 specifically, so as to hack the payload before sending it. 

Thus, unluckily, we're unable to provide a solution anytime soon until we change the validator. 

I'm closing this issue as won't do. Thank you for bringing this up.
