### ISSUE TITLE
Invalid scalar inheritance base type when specializing int64 type

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1736]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

* **What is the current behavior?**

When attempting to narrow `int64` to `int32`, invalid type inheritance occurs.

The following RAML reproduces the issue:
```yaml
#%RAML 1.0 Library

types:
  IntObject:
    properties:
      prop1: Int64Type

  DerivedIntObject:
    type: IntObject
    properties:
      prop1: Int32Type

  Int64Type:
    type: integer
    format: int64

  Int32Type: # Throws "Resolution error: Invalid scalar inheritance base type http://www.w3.org/2001/XMLSchema#integer < http://www.w3.org/2001/XMLSchema#long (http://a.ml/vocabularies/amf/resolution#invalid-type-inheritance)"
    type: integer
    format: int32
```

Is this done on purpose or can this case be considered as bug?

* **Please tell us about your environment:**
  
  - AMF Version: 5.2.4
  - AMF Distribution: JVM and JS
  - Operating System: Windows 10 22H2
