### ISSUE TITLE
Cannot compute inheritance from union when specializing a union property with the `type` keyword

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1809]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

Starting with version 5.3.0, the "Cannot compute inheritance from union" warning appears when attempting to specialize a union property of parent object that uses the `type` keyword.

The following RAML triggers this warning on the `MyObject` type:
```yaml
#%RAML 1.0 Library

types:
  BaseObject:
    additionalProperties: false
    properties:
      data?:
        type: any | nil

  SpecializedObject:
    type: BaseObject
    additionalProperties: false
    properties:
      data: MyObject

  MyObject: # <-- Cannot compute inheritance from union happens here
    additionalProperties: false
    properties:
      prop: string
```

The notable thing is that if you use an inline union in the `data?` property of `BaseObject` or specify a union in the derived `SpecializedObject`, the warning is gone. Here's an extended example that shows valid combinations:
```yaml
#%RAML 1.0 Library

types:
  BaseObject:
    additionalProperties: false
    properties:
      data?: any | nil # <-- Makes the warning disappear
      other_data?:
        type: any | nil

  SpecializedObject:
    type: BaseObject
    additionalProperties: false
    properties:
      data: MyObject
      other_data?: MyObject | nil # <-- Also works, but not what I want

  MyObject:
    additionalProperties: false
    properties:
      prop: string
```

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

The following code reproduces the issue:
```js
import amf from "amf-client-js";

const raml = `
#%RAML 1.0 Library

types:
  BaseObject:
    additionalProperties: false
    properties:
      data?:
        type: any | nil

  SpecializedObject:
    type: BaseObject
    additionalProperties: false
    properties:
      data: MyObject

  MyObject:
    additionalProperties: false
    properties:
      prop: string
`;

(async () => {
  const client = amf.RAMLConfiguration.RAML10().baseUnitClient();

  const data = await client.parseContent(raml);
  const result = await client.validate(data.baseUnit)
  console.log(data.merge(result).toString())
})();
```

Results in the following validation result:
```
Model: http://a.ml/amf/default_document
Conforms: true
Number of results: 1

Level: Warning

- Constraint: http://a.ml/vocabularies/amf/resolution#invalid-type-inheritance-warning
  Message: Cannot compute inheritance from union
  Severity: Warning
  Target: http://a.ml/amf/default_document#/declares/shape/MyObject
  Property: http://a.ml/vocabularies/shapes#inherits
  Range: [(17,2)-(22,0)]
  Location: http://a.ml/amf/default_document
```

* **What is the expected behavior?**

There should be no warnings.

* **Please tell us about your environment:**
  
  - AMF Version: 5.3.0
  - AMF Distribution: JS
  - Operating System: Windows 10 22H2
