### ISSUE TITLE
Recursive object property

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#1817]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] question
  - [ ] other

* **What is the current behavior?**

When tinkering with recursive types, I noticed that there're some rules that the parser follows and RAML 1.0 spec unfortunately doesn't say anything about handling of recursive types.

The following RAML will result in validation error on `NestedField` property if it's a recursive object:
```yaml
#%RAML 1.0 Library

types:
  OtherType:
    type: object
    properties:
      NestedField: OtherType # Invalid cyclic references in shapes: OtherType -> NestedField -> OtherType
      Children:
        type: array
        items:
          type: OtherType # Validates just fine
```

However, if you make `NestedField` optional, it passes validation:
```yaml
#%RAML 1.0 Library

types:
  OtherType:
    type: object
    properties:
      NestedField?: OtherType # Now also validates just fine!
      #NestedField: # Will also work, so it's definitely about required
      #  type: OtherType
      #  required: false
      Children:
        type: array
        items:
          type: OtherType # Validates just fine
```

Is this expected behavior?

* **Please tell us about your environment:**
  
  - AMF Version: 5.4.0-1
  - AMF Distribution: JS
  - Operating System: Windows 10 22H2
