### ISSUE TITLE
Using an Array in a custom extension

### ISSUE THREAD

**Issue by gortegasntt** [aml-org/amf#1820]
### Goal

Hi, I want to validate that an extension only uses some defined values, for example:

```
x-custom:
    - a
    - b
    - c
```

And I only want to let "a", "b" or "c" in that extension.

### Problem

When I try to define the Annotation, I don't know what should I put in "range", as it only allow some values as string, integer, any or a NodeMapping. I suppose that if there is a way, is should be some kind of NodeMapping, but I don't know what should I put in it to make it work.

**Comment by tomsfernandez** [comment]
Hi @gortegasntt can you share with me your extension schema?

**Comment by gortegasntt** [comment]
Well @tomsfernandez , I don' have much, but i imagine it would be something like:
```
annotationMappings:
  CustomeAnnotation:
    domain: apiContract.WebAPI
    propertyTerm: apiContract.Custom
    range: ???
```
I suppose that there is something I can add in range to make it work, but array is not a possible valuep

**Comment by deiteris** [comment]
I think you need to use `allowMultiple: true` to allow for multiple values:
https://github.com/aml-org/aml-spec/blob/master/dialects.md#multiple-node-nesting

So full example of what you want to achieve probably will be:
```
annotationMappings:
  CustomeAnnotation:
    domain: apiContract.WebAPI
    propertyTerm: apiContract.Custom
    range: string
    allowMultiple: true    # Allows for multiple values in the node
```

Annotation mappings behave almost the same way as property mappings, and their properties are documented here:
https://github.com/aml-org/aml-spec/blob/master/dialects.md#property-mappings.
