### ISSUE TITLE
missing semantic sugar for URI parameters

### ISSUE THREAD

**Issue by sichvoge** [aml-org/amf#22]
Assume the following RAML:

```yaml
#%RAML 1.0

title: ACME Banking HTTP API
version: 1.0
mediaType: application/json

/customers:
  displayName: Customer Resource
  /{customer_id}:
    uriParameters:
      customer_id: string
```

Executing `./amf.js validate -cp file://acme-profile.raml -in RAML example/api.raml`, AMF validator returns `java.lang.Exception: Expected map but found: "string"`.

Modifying `customer_id: string` to use the extended form with `type` validates correctly.
