### ISSUE TITLE
empty value for any resource in RAML should be valid

### ISSUE THREAD

**Issue by sichvoge** [aml-org/amf#24]
Assume the following RAML:

```yaml
#%RAML 1.0

version: 1.0
#mediaType: application/json

/customers:
  displayName: Customer Resource
  /{customer_id}:
```

Despite the title is missing, the following command `./amf.js validate -p RAML -in RAML api.raml` fails with `java.lang.Exception: Expected map but found: ""`. 

There is no value for `/{customer_id}` which should be still valid in RAML.
