### ISSUE TITLE
"Properties allowedTargets not supported" in annotationType declaration

### ISSUE THREAD

**Issue by postatum** [aml-org/amf#459]
`amf-client-js@3.1.8`

When running following JS code with RAML file, I get validation error saying:
```
Properties allowedTargets not supported in a RAML 1.0 nodeShape node
```
I think it should work because [RAML spec here](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md#declaring-annotation-types) says:
`An annotation type declaration has the same syntax as a data type declaration, and its facets have the same syntax as the corresponding ones for data types, but with the addition of the allowedTargets facet.`

JS code:
```js
const amf = require('amf-client-js')

async function main () {
  await amf.AMF.init()
  const model = await amf.AMF.raml10Parser().parseFileAsync(`file://./api.raml`)
  try {
    const report = await amf.AMF.validate(
      model, amf.ProfileNames.RAML10, amf.MessageStyles.RAML)
  } catch (e) {
    console.log(e.toString())
  }
  if (!report.conforms) {
    report.results.map(res => {
      console.log(`${res.level} - ${res.message}`)
    })
  }
}

main()
```

RAML:
```
#%RAML 1.0
title: MyApi
types:
  MyType:
    properties:
      numberProp: number

annotationTypes:
   MyAnnotation:
     type: MyType
     allowedTargets: API

traits:
   trait1:
      headers:
        header1:

(MyAnnotation):
  numberProp: 11
```
