### ISSUE TITLE
Type example is a string instead of any structured data

### ISSUE THREAD

**Issue by jarrodek** [aml-org/amf#487]
Following declaration:

```yaml
#%RAML 1.0
title: Query example
version: v1
baseUri: http://domain.api.domain.com/{version}/

types:
  Image:
    type: object
    properties:
      type:
        type: string
        enum: [thumb, full, hd, 4k]
      url: string
  Product:
    displayName: A product resource
    description: A single product representing an item in the store.
    type: object
    properties:
      id:
        description: |
          Product id. It is a UUID of the database record.
          __This property will be ignored when creating an object.__
          It will be available when the product is stored in the datastore.
        pattern: "[0-9a-zA-Z-]+"
      name:
        type: string
        description: Product name
        example: Acme product - mentol flavor, 500 ml.
        required: true
      quantity:
        type: number
        description: |
          The quantity of the product in the one unit of measurement.
          See `unit` property for more information.
        example: 500
        required: true
      unit:
        type: string
        description: The unit of measuremet for the quantity property.
        example: ml
        required: true
      upc:
        type: string
        pattern: "[0-9]{12,12}"
        description: |
          The Universal Produc Code. It consists of 12 numerical digits. However, because of the
          integer precision limitation in JavaScript it is represented as a string.
        example: "042100005264"
        required: true
      available:
        type: boolean
        description: |
          Product current availability in the store.
          Product may be not available but the users still can order it with later delivery date.
        required: true
        example: true
      images: Image[]
    example:
      id: we2322-4f4f4f-f4f4ff-f4f4ff4
      name: Acme Product
      quantity: 200
      unit: ml
      upc: "123456789101"
      available: true
      images:
        - type: thumb
          url: https://domain.com
```
Produces following example model:

```json
"http://raml.org/vocabularies/document#examples": [
          {
            "@id": "file://raml-examples/raml-body-params/api.raml#/declarations/Product/example/null",
            "@type": [
              "http://raml.org/vocabularies/document#Example",
              "http://raml.org/vocabularies/document#DomainElement"
            ],
            "http://raml.org/vocabularies/document#value": [
              {
                "@value": "      id: we2322-4f4f4f-f4f4ff-f4f4ff4\n      name: Acme Product\n      quantity: 200\n      unit: ml\n      upc: \"123456789101\"\n      available: true\n      images:\n        - type: thumb\n          url: https://domain.com\n"
              }
            ],
            "http://raml.org/vocabularies/document#strict": [
              {
                "@value": true
              }
            ]
          }
        ]
```
This information is useless until I parse it as a YAML string and then transform it to JS object (for example). RAML JS parser results with example being a JS object (map of key - value pairs). INHO AMF should process structured type example as objects and not strings.
