### ISSUE TITLE
apimf-411

### ISSUE THREAD

**Issue by antoniogarrote** [aml-org/amf#496]
Having the following Dialect Library

```yaml
#%RAML Library / RAML 1.0 Dialect

uses:
  anypoint-vocabulary: ./anypoint-vocabulary.raml

nodeMappings:

  asset:
    classTerm: anypoint-vocabulary.Asset
    mapping:
      group:
        propertyTerm: anypoint-vocabulary.group
        mandatory: true
        range: string
      artifact:
        propertyTerm: anypoint-vocabulary.artifact
        mandatory: true
        range: string
      version:
        propertyTerm: anypoint-vocabulary.version
        mandatory: true
        range: string
      classifier:
        propertyTerm: anypoint-vocabulary.classifier
        mandatory: false
        range: string
      packaging:
        propertyTerm: anypoint-vocabulary.packaging
        mandatory: true
        range: string
      composedBy:
        propertyTerm: anypoint-vocabulary.asset
        mandatory: false
        range: asset
```

and then used it as a fragment in a library

```yaml
#%RAML 1.0 Dialect

dialect: Mule Agent Configuration
version: 0.1

uses:
    mule-runtime: ./mule-runtime-vocabulary.raml
    anypoint-vocabulary: ./anypoint-vocabulary.raml
    anypoint-dialect: ./anypoint-dialect.raml

external:
  schema-org: http://schema.org/

raml:
  document:
    encodes: muleAgentConfiguration
    declares:
      assets: anypoint-dialect.asset

  fragments:
    encodes:
      Asset: anypoint-dialect.asset

nodeMappings:

  muleAgentConfiguration:
    classTerm: mule-runtime.Agent
    mapping:
      asset:
        propertyTerm: anypoint-vocabulary.asset
        mandatory: false
        range: anypoint-dialect.asset
```

throws the following exception:

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.Exception: Encoded domain element is not a dialect domain entity ExternalDomainElement(amf.core.parser.Fields@1b0076fe,amf.core.parser.Annotations@2ca00669)
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
```

With the following requesT:

```yaml
#%Mule Agent Configuration 0.1

asset: include ./salesforce-asset.raml
```
[Archive.zip](https://github.com/mulesoft/amf/files/1647167/Archive.zip)
