### ISSUE TITLE
Remove intermediate property in dialect modules

### ISSUE THREAD

**Issue by antoniogarrote** [aml-org/amf#507]
Right now when parsing a dialect library like:

```yaml
#% RAML Library / My Dialect 0.1

syntaxToIntroduceDeclaration:
  myDeclaration: 
     props: here
```

We are generating a module definition in JSON-LD like:

```turtle
mymodule.raml a raml-doc:Module ;
             raml-doc:declares mylibrary.raml#.
mylibrary.raml# a raml-doc:module ;
            raml-doc:syntaxToIntroduceDeclaration mylibrary#myDeclaration .
```

That intermediate node of type ```raml-doc:module``` and the ```raml-doc:syntaxToIntroduceDeclaration``` are an error.

The expected graph would be:

```turtle
mymodule.raml a raml-doc:Module ;
            raml-doc:declares mylibrary#myDeclaration .
```

Additional annotations can be added to track the information about the property in the syntax that introduces the declaration (syntaxToIntroduceDeclaration)
