### ISSUE TITLE
Custom validation profile throws violation when defining named example in RAML overlay

### ISSUE THREAD

**Issue by wes566** [aml-org/amf#589]
1. use an overlay.raml to add a named example to a Type
2. use a custom validation profile that extends the RAML validation profile, something as simple as:
    ```yaml
    #%Validation Profile 1.0
    profile: custom-validations
    extends: RAML
    ```

3. use amf-client-js to validate with that custom validation profile

Expected:
No violations

Actual:
`example-validation-error` violation is present

Switching to use the "RAML" validation profile produces no violations.

I have created a simple repro repo at https://github.com/wes566/amf-named-example-bug-repro
