### ISSUE TITLE
Validation error when ID template variable used as map key

### ISSUE THREAD

**Issue by ryan-slack-big** [aml-org/amf#858]
**I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

**Example**
In the following dialect `NamedCode` has `idTemplate: http://a.ml/codes/{name}`,  and `MapKeyIdTempleateTestNode`  has `mapKey: name`.

*Dialect:*
```
#%Dialect 1.0
dialect: Map Key IdTempleate Test
version: 1.0

documents:
  root:
    encodes: MapKeyIdTempleateTestNode

nodeMappings:
  MapKeyIdTempleateTestNode:
    mapping:
      colors:
        range: NamedCode
        mapKey: name

  NamedCode:
    idTemplate: http://a.ml/codes/{name}
    mapping:
      name:
        range: string
        unique: true
        mandatory: true
      code:
        range: string
        mandatory: true
```

*Document:*
```
#%Map Key IdTempleate Test 1.0
colors:
  red:
    code: "FF0000"
```

**Actual behavior:**

 `Missing ID template variable 'name' in node`
```
- Source: http://a.ml/vocabularies/amf/aml#dialect-error
  Message: Missing ID template variable 'name' in node
  Level: Violation
  Target: null
  Property: 
  Position: Some(LexicalInformation([(5,0)-(6,0)]))
  Location: file://fiddle/mapkey-idtemplate.yaml
```

**Expected behavior:**
Create a id with the value `http://a.ml/codes/red`

*Environment:*
  - AMF Version: 4.7.1 (local build from 4a8083c28)
  - AMF Distribution: JVM
  - Operating System: Linux
