### ISSUE TITLE
Trait does not apply correctly to new endpoint method in extension fragment

### ISSUE THREAD

**Issue by deiteris** [aml-org/amf#976]
Your issue may already be reported! Please search on Github issues before creating one.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] question
  - [ ] other

* **What is the current behavior?**

I've encountered this in https://github.com/mulesoft/api-console/issues/689 when working with the API console. I'll duplicate the description just in case.

* **If the current behavior is a bug, please provide the minimal steps to reproduce with AMF code. Please don't upload AMF code mixed with yours.**

Given the following main RAML file:

```yaml
#%RAML 1.0
title: My API
mediaType: application/json
baseUri: https://production.com
protocols: [ HTTPS ]

/types:
  get:
```

I am trying to extend it with the following fragment:

```yaml
#%RAML 1.0 Extension
extends: api.raml # RAML API definition to extend

title: My Dev API # DEVELOPMENT-only API definition
baseUri: http://localhost # "localhost" baseUri
protocols: [ HTTP, HTTPS ] # allow unsecured HTTP

traits:
  customHeaders:
    headers:
      X-My-Custom-Header:

/types:
  get:
    is: [customHeaders]
  post:
    is: [customHeaders]
```

Both RAML definitions parse without any errors, but the AMF Graph for the extension fragment doesn't contain `apiContract:header` for new `POST /types`, while `GET /types` does contain it.

![image](https://user-images.githubusercontent.com/6103913/120475594-38d4d780-c3b2-11eb-8b30-846b2fec93b2.png)

I suspect that this also may happen with other trait properties. You can see `doc:extends` that lists the applied trait, but it seems to not get merged into the endpoint method.

Generated AMF Graph of the extension fragment: https://pastebin.com/3M56ZuuW

* **What is the expected behavior?**

The trait with a header should be applied correctly to the newly created `POST /types`.

* **Please tell us about your environment:**
  
  - AMF Version: 4.7.3
  - AMF Distribution: JVM
  - Operating System: Windows 10 20H2
